apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
  labels:
    app: payment-app
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment-app
  template:
    metadata:
      labels:
        name: payment-app
    spec:
      containers:
      - name: payment-ecommerce
        imagePullPolicy: Always
        image: eldimious/payment-ecommerce:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '200m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '512Mi'
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: POSTGRES_PORT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: PAYMENTS_POSTGRES_DB
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: KAFKA_BROKERS
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: POSTGRES_PASSWORD
          - name: QUARKUS_STRIPE_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: QUARKUS_STRIPE_WEBHOOK_SECRET
          - name: QUARKUS_STRIPE_API_KEY
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: QUARKUS_STRIPE_API_KEY