AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  address-validation-lambda

  Validate user address

Parameters:
  SHIPPO_API_TOKEN:
    Description: Required. Api key for Shippo api
    Type: String
  STAGE:
    Description: Required. Stage for lambda
    Type: String

Resources:
  AddressValidation:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: addressValidation/
      Handler: dist/presentation/functions/app.lambdaHandler
      Runtime: nodejs16.x
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          SHIPPO_API_TOKEN: !Ref SHIPPO_API_TOKEN
          STAGE: !Ref STAGE
      Events:
        Api:
          Type: Api
          Properties:
            Path: /address/validation
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddressValidationApi:
    Description: "API Gateway endpoint URL for Prod stage for Address Validation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/address/"