apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  labels:
    app: debezium-service
  name: debezium-service
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: debezium-connector