apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app
  labels:
    app: email-app
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      name: email-app
  template:
    metadata:
      labels:
        name: email-app
    spec:
      containers:
      - name: email-ecommerce
        imagePullPolicy: Always
        image: eldimious/email-ecommerce:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '200m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '512Mi'
        env:
          - name: USERS_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: USERS_SERVICE_URL
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: KAFKA_BROKERS
          - name: QUARKUS_MAILGUN_DOMAIN_NAME
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: QUARKUS_MAILGUN_DOMAIN_NAME
          - name: QUARKUS_MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: QUARKUS_MAILGUN_API_KEY